// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go.adenix.dev/adderall/config"
	"go.adenix.dev/adderall/logger"
	"go.adenix.dev/adderall/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, func()) {
	appConfig := config.NewAppConfig()
	serverConfig := NewServerConfig(appConfig)
	tracer := NewTracer()
	loggerLogger, cleanup := logger.NewLogger(tracer)
	factory := NewServerFactory(serverConfig, loggerLogger, tracer)
	clientConfig := NewClientConfig(appConfig)
	clientFactory := NewClientFactory(clientConfig, loggerLogger, tracer)
	myService := MyService{
		ServerFactory: factory,
		ClientFactory: clientFactory,
	}
	serverServer := NewServer(myService)
	return serverServer, func() {
		cleanup()
	}
}

// wire.go:

var commonSet = wire.NewSet(config.NewAppConfig, logger.NewLogger, NewTracer,
	NewServerConfig,
	NewServerFactory,
	NewClientConfig,
	NewClientFactory,
)
